# -*- coding: utf-8 -*-
"""Afine.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNEsWC8Y4RqOnI-w9F8jHY6Efx79UqVm
"""

def mod_inverse(a, m):
    for i in range(1, m):
        if (a * i) % m == 1:
            return i
    return None

def affine_decrypt(ciphertext, a, b):
    decrypted_text = ""
    m = 26  # Jumlah huruf dalam alfabet

    a_inverse = mod_inverse(a, m)
    if a_inverse is None:
        raise ValueError("Key 'a' tidak memiliki invers modulo 26")

    for char in ciphertext:
        if char.isalpha():
            char = char.upper()
            decrypted_char = chr(((a_inverse * (ord(char) - ord('A') - b)) % m) + ord('A'))
            decrypted_text += decrypted_char
        else:
            decrypted_text += char

    return decrypted_text

# Meminta pengguna memasukkan teks sandi
ciphertext = input("Masukkan teks sandi Affine Cipher: ")
a = int(input("Masukkan nilai 'a' : "))
b = int(input("Masukkan nilai 'b' : "))

# Mendekripsi teks
decrypted_text = affine_decrypt(ciphertext, a, b)

# Menampilkan hasil dekripsi
print("Teks Sandi:", ciphertext)
print("Teks Terdekripsi:", decrypted_text)