# -*- coding: utf-8 -*-
"""Vigenere_Ahmadfahrul.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wv3RaREAPBhMVMHCOjLMYMiCafbH6RIm
"""

# Fungsi untuk mengenkripsi teks dengan Vigenere Cipher
def vigenere_encrypt(text, key):
    encrypted_text = ""
    key_length = len(key)

    for i in range(len(text)):
        char = text[i]
        key_char = key[i % key_length]
        encrypted_char = chr(((ord(char) + ord(key_char)) % 26) + ord('A'))
        encrypted_text += encrypted_char

    return encrypted_text

# Fungsi untuk mendekripsi teks dengan Vigenere Cipher
def vigenere_decrypt(encrypted_text, key):
    decrypted_text = ""
    key_length = len(key)

    for i in range(len(encrypted_text)):
        char = encrypted_text[i]
        key_char = key[i % key_length]
        decrypted_char = chr(((ord(char) - ord(key_char)) % 26) + ord('A'))
        decrypted_text += decrypted_char

    return decrypted_text

# Daftar pengguna (gunakan database yang sesungguhnya dalam aplikasi nyata)
users = {
    "UPB": {"password": "KEY", "encrypted_password": vigenere_encrypt("MEGAH", "KEY")},
    "tamimi": {"password": "SECRET", "encrypted_password": vigenere_encrypt("PASSWORD123", "SECRET")},
}

# Fungsi untuk melakukan login
def login(username, password):
    if username in users:
        stored_encrypted_password = users[username]["encrypted_password"]
        key = users[username]["password"]
        encrypted_password = vigenere_encrypt(password, key)
        if encrypted_password == stored_encrypted_password:
            return True
    return False

# Program utama
while True:
    print("Selamat datang di sistem login sederhana.")
    username = input("Masukkan username: ")
    password = input("Masukkan password: ")

    if login(username, password):
        print("Login berhasil!")
        break
    else:
        print("Login gagal. Silakan coba lagi.")